GET http://localhost:3001/api/notes

###
DELETE  http://localhost:3001/api/notes/1

###
# @name login
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "salainen"
}
###
@authToken = {{login.response.body.token }}
@username = {{user.response.body.$.[0].username}}
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "content": "HTML is easy",
    "date": "2022-05-30T17:30:31.098Z",
    "important": true,
    "username": "{{username}}"
}

###
# @name user
GET http://localhost:3001/api/users


###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}
