[tool.poetry]
name = "homeworks"
version = "0.1.0"
description = ""
authors = ["cndoit18 <cndoit18@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
